### ISSUE TITLE
Cannot access the port opened with commands provided in the instruction

### ISSUE THREAD

**Issue by eulerreich** [sagemath/docker#3] opened 2015-09-04 12:55 UTC
I'm on a Ubuntu 14.04 VM on a windows 8.1 host. I have the latest version 1.8.1 of docker, build d12ea79.

I can run the first command in the instructions

`docker run --rm -i -t sagemath/sage`

If I run
``docker run --rm -p 127.0.0.1:8080:8080 -d -t sagemath/sage --notebook=sagenb``
or
``docker run --rm -p 127.0.0.1:8080:8080 -d -t sagemath/sage --notebook=ipython --ip='*' --port=8080``

I get an error `Conflicting options: --rm and -d`. If I remove the --rm option, then everything runs, but I cannot access the 8080 port on localhost.

I have run the port mapping part of the docker tutorial and haven't gotten any problems. In particular, when I run 
`docker run -d -P training/webapp python app.py`
as per the tutorial, I can access the port corresponding to the python container.

So it doesn't seem like there's any hardware or virtualization problem on my part.

**Comment by gaviriar** [comment] 2016-06-23 18:35
Did you find a solution to this problem, I'm encountering the exact same issue and I have not been able to figure out the cause. 

Any help would be appreciated.

Thanks!

**Comment by embray** [comment] 2016-06-27 12:24
@gaviriar For what it's worth, I don't think this image is still being maintained, and I'm about to mark it more clearly as deprecate.  For the a more up-to-date image, `docker pull sagemath/sagemath`--it contains the image built for sage 7.2.

Not 100% sure if that will resolve the issue but it might.

**Comment by embray** [comment] 2016-06-27 12:25
Seems to be duplicate of #2 .

**Closed by embray** 2016-06-27 12:25 UTC
